### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'utility')

### ISSUE THREAD

**Issue by rozap** [rebrowser/rebrowser-patches#61]
When starting it up only in headless mode, I see the following and then all pages fail to load with an HTTP2 Protocol Error:

```
[rebrowser-patches][frames._context] cannot get world, error: TypeError: Cannot set properties of undefined (setting 'utility')
   at priv/python/venv/lib/python3.11/site-packages/rebrowser_playwright/driver/package/lib/server/frames.js:715:38                                              
    at async priv/python/venv/lib/python3.11/site-packages/rebrowser_playwright/driver/package/lib/server/frames.js:1530:72                                       
    at async Frame.retryWithProgressAndTimeouts (priv/python/venv/lib/python3.11/site-packages/rebrowser_playwright/driver/package/lib/server/frames.js:1096:24)  
    at async ProgressController.run (priv/python/venv/lib/python3.11/site-packages/rebrowser_playwright/driver/package/lib/server/progress.js:82:22)              
    at async Frame.waitForFunctionValueInUtility (priv/python/venv/lib/python3.11/site-packages/rebrowser_playwright/driver/package/lib/server/frames.js:1596:20) 
    at async Screenshotter._fullPageSize (priv/python/venv/lib/python3.11/site-packages/rebrowser_playwright/driver/package/lib/server/screenshotter.js:147:26)   
    at async priv/python/venv/lib/python3.11/site-packages/rebrowser_playwright/driver/package/lib/server/screenshotter.js:167:30                                 

Exception, exit Page.goto: net::ERR_HTTP2_PROTOCOL_ERROR at www.somesite.com
```

But strangely, everything works fine in headful mode. This is on Ubuntu 20.04 and rebrowser_playwright==1.48.100.
I haven't dug into this too much yet, just writing it down now before I forget. Will do some digging in the coming days.

**Comment by MaxLiebsch** [comment]
@rozap 
Are you sure you are not simply blocked? 
net::ERR_HTTP2_PROTOCOL_ERROR
seems to occur in the case of blocking.

But I'm not sure, so if you would enlight me, would be cool.

**Comment by rozap** [comment]
It seems like that's likely, but wouldn't that point to the patch not patching the user-agent correctly and leaking the headless flag?

**Comment by rozap** [comment]
Yep, finally had more time to dig into this tonight, and it's definitely being blocked when in headless mode. I'll just use a virtual display instead of headless. Not sure how it's being detected.
